% shShowV1PopulationResponse(populationResponse)        
%
% show the response of a large population of V1 neurons generated by
% shV1PopulationRepsonse.
%
% Example of use:
% pars = shPars;
% dims = shGetDims(pars, 'mtPattern', [1 1 101]);
% stimulus = mkDots(dims, 0, 1);
% vels = linspace(-3, 3, 15);
% [populationResponse, v1Directions] = shV1PopulationResponse(stimulus, pars);
% shShowV1PopulationResponse(populationResponse);
% rotate3d on

function shShowV1PopulationResponse(populationResponse)

ntheta = sqrt(size(populationResponse,1));
nphi = ntheta;
populationResponse = (populationResponse./max2(abs(populationResponse))).^2;

phi = linspace(-pi/2, pi/2, nphi+1);
theta = linspace(0, 2.*pi, ntheta+1);
y = zeros(4, nphi.*ntheta);
x = y;
t = y;
for j = 1:nphi
    for i = 1:ntheta
        az = [theta(i); theta(i+1); theta(i+1); theta(i)];
        el = [phi(j); phi(j); phi(j+1); phi(j+1)];
        yxt = sphere2rec([az, el]);
        pt = (j-1).*nphi+i;
        y(:,pt) = yxt(:,1);
        x(:,pt) = yxt(:,2);
        t(:,pt) = yxt(:,3);
    end
end


colormap bone
p = patch(x, y, t, populationResponse');
set(p, 'edgecolor', 'none');

set(gcf, 'color', 'w');
axis([-1.5 1.5 -1.5 1.5 -1.5 1.5]);
axis off
axis vis3d
crossAxes('color', 'k');
labelCrossAxes('\omega_x', '\omega_y', '\omega_t', 'default', 'fontsize', 16);
rotate3d on
