function [fix_x, fix_y, fix_duration,is_first_fix] = read_vanhat_gp_fixations(gp_filename,sub_name)

%Function to load the grouped fixation data from the .mat files for the
%DOVES database

%INPUT  - The name of a .mat file generated by group.eye_vanhat (Data structure stored in GROUPED_EYE_DATA)
%       - sub_name - A valid subject name (IVDL, UR etc.)
%       -          - If blank, data is returned for everyone
%OUTPUT - fix_x,fix_y & fix_duration for this subject


if (nargin < 2) sub_name = 'everyone'; end



load (gp_filename); %Data loaded is subj_name_list and gp_data

fix_data = [];
is_first_fix =[];

%Decide to either read the data for one subject or all the subjects
if strcmp(sub_name,'everyone')
    for i = 1:length(subj_names_list)
       temp_data = gp_data{i};
        if (length(temp_data)>0)
            fix_data = [fix_data temp_data];
            %is_first_fix = [is_first_fix [1 zeros(1,length(temp_data)-1)]];
            is_first_fix = [is_first_fix [1 zeros(1,size(temp_data,2)-1)]];
            
        end
        [length(fix_data) length(is_first_fix)];
    end

elseif ~(strcmp(sub_name,'everyone')) % A particular subject was selected
    sub_index = (find(strcmp(sub_name,subj_names_list)));
    % In case there is no subject with the name return []
    if (sub_index == 0);
        fix_x=[];fix_y=[];fix_duration=[];
        return;
    elseif (sub_index ~= 0) %found the subject
        temp_data = gp_data{sub_index};
        if (length(temp_data)>0)
            fix_data = [fix_data temp_data];
            %is_first_fix = [is_first_fix [1 zeros(1,length(temp_data)-1)]];
            is_first_fix = [is_first_fix [1 zeros(1,size(temp_data,2)-1)]];
        end

    end;
end

%Get the eye data, now
fix_x = fix_data(1,:);
fix_y = fix_data(2,:);
fix_duration = fix_data(3,:);

